"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BarChart3, Car, Check, Download, LayoutDashboard, LogOut, Mail, Plus, Save, Settings, Trash2, Upload } from "lucide-react";
import type { Vehicle } from "@/data/vehicles";
import { formatKes } from "@/data/vehicles";
import { defaultSettings, getLeads, getSettings, getVehicles, saveSettings, saveVehicles, updateLead, type Lead, type SiteSettings } from "@/lib/storage";

const blank:Vehicle={id:"",make:"",model:"",name:"",year:new Date().getFullYear(),mileage:0,fuel:"Petrol",transmission:"Automatic",body:"SUV",price:0,location:"Kangundo Road, Nairobi",source:"Imported",status:"Available",description:"",images:[]};

export default function AdminPage(){
 const [tab,setTab]=useState("dashboard"),[vehicles,setVs]=useState<Vehicle[]>([]),[leads,setLeads]=useState<Lead[]>([]),[settings,setSettings]=useState<SiteSettings>(defaultSettings),[editing,setEditing]=useState<Vehicle|null>(null),[notice,setNotice]=useState("");
 const refresh=()=>{setVs(getVehicles());setLeads(getLeads());setSettings(getSettings())};
 useEffect(()=>{refresh()},[]);
 const newLeads=useMemo(()=>leads.filter(x=>x.status==="New").length,[leads]);
 function saveVehicle(e:FormEvent){e.preventDefault();if(!editing)return;const item={...editing,id:editing.id||`${editing.make}-${editing.model}-${Date.now()}`.toLowerCase().replace(/[^a-z0-9]+/g,"-")};const next=vehicles.some(v=>v.id===item.id)?vehicles.map(v=>v.id===item.id?item:v):[item,...vehicles];saveVehicles(next);setVs(next);setEditing(null);setNotice("Vehicle saved.")}
 function removeVehicle(id:string){if(!confirm("Remove this vehicle?"))return;const next=vehicles.filter(v=>v.id!==id);saveVehicles(next);setVs(next)}
 function exportData(){const b=new Blob([JSON.stringify({vehicles,leads,settings,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="safi-motors-backup.json";a.click()}
 function importData(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));if(Array.isArray(p.vehicles))saveVehicles(p.vehicles);if(Array.isArray(p.leads))localStorage.setItem("safi_motors_leads_v1",JSON.stringify(p.leads));if(p.settings)saveSettings(p.settings);refresh();setNotice("Backup restored.")}catch{setNotice("Invalid backup file.")}};r.readAsText(f)}
 return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="brand"><span className="brand-mark">SM</span><span><strong>Safi Motors</strong><small>Admin</small></span></Link><div className="admin-menu"><button className={tab==="dashboard"?"selected":""} onClick={()=>setTab("dashboard")}><LayoutDashboard/>Dashboard</button><button className={tab==="vehicles"?"selected":""} onClick={()=>setTab("vehicles")}><Car/>Vehicles</button><button className={tab==="leads"?"selected":""} onClick={()=>setTab("leads")}><Mail/>Enquiries {newLeads>0&&<b>{newLeads}</b>}</button><button className={tab==="settings"?"selected":""} onClick={()=>setTab("settings")}><Settings/>Settings</button></div><Link href="/" className="admin-exit"><LogOut/>View website</Link></aside>
 <section className="admin-main"><div className="admin-top"><div><span className="eyebrow">SAFI MOTORS MANAGEMENT</span><h1>{tab==="dashboard"?"Dashboard":tab==="vehicles"?"Vehicles":tab==="leads"?"Customer enquiries":"Settings"}</h1></div><div className="admin-actions"><button onClick={exportData}><Download size={16}/>Backup</button><label><Upload size={16}/>Restore<input type="file" accept="application/json" onChange={importData} hidden/></label></div></div>{notice&&<div className="admin-notice"><Check size={16}/>{notice}</div>}
 {tab==="dashboard"&&<div className="admin-grid"><Stat icon={<Car/>} value={vehicles.length} label="Vehicles"/><Stat icon={<Mail/>} value={leads.length} label="Enquiries"/><Stat icon={<BarChart3/>} value={newLeads} label="New enquiries"/><div className="admin-panel wide"><h2>Quick actions</h2><div className="quick-actions"><button onClick={()=>{setEditing({...blank});setTab("vehicles")}}><Plus/>Add vehicle</button><button onClick={()=>setTab("leads")}><Mail/>View enquiries</button><button onClick={()=>setTab("settings")}><Settings/>Business settings</button></div></div></div>}
 {tab==="vehicles"&&<div className="admin-panel"><div className="panel-heading"><div><h2>Vehicle catalogue</h2><p>Browser demo storage. Connect a production database before multi-device use.</p></div><button className="gold-button" onClick={()=>setEditing({...blank})}><Plus size={17}/>Add vehicle</button></div><div className="admin-table">{vehicles.map(v=><div className="admin-row" key={v.id}><img src={v.images[0]||"https://placehold.co/120x80/191c1f/d7ad55?text=Car"} alt=""/><div><strong>{v.name}</strong><span>{v.year} · {v.body} · {formatKes(v.price)}</span></div><span className={"status "+v.status.toLowerCase()}>{v.status}</span><button onClick={()=>setEditing(v)}>Edit</button><button onClick={()=>removeVehicle(v.id)} aria-label="Delete"><Trash2 size={16}/></button></div>)}</div></div>}
 {tab==="leads"&&<div className="admin-panel"><div className="panel-heading"><div><h2>Customer enquiries</h2><p>Requests are stored in this browser until a production database is connected.</p></div></div>{leads.length?<div className="lead-list">{leads.map(l=><article className="lead-card" key={l.id}><div><span className="lead-type">{l.type}</span><h3>{l.name}</h3><p>{l.phone}{l.email?" · "+l.email:""}</p><p>{l.message||"No message provided."}</p><small>{new Date(l.createdAt).toLocaleString()}</small></div><select value={l.status} onChange={e=>{updateLead(l.id,e.target.value as Lead["status"]);setLeads(getLeads())}}><option>New</option><option>Contacted</option><option>Closed</option></select></article>)}</div>:<div className="empty-state"><Mail/><h3>No enquiries yet</h3><p>New requests will appear here.</p></div>}</div>}
 {tab==="settings"&&<form className="admin-panel settings-form" onSubmit={e=>{e.preventDefault();saveSettings(settings);setNotice("Settings saved.")}}><h2>Business contact settings</h2><p>Enter confirmed Safi Motors details when supplied.</p><label>Phone<input value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})}/></label><label>WhatsApp<input value={settings.whatsapp} onChange={e=>setSettings({...settings,whatsapp:e.target.value})}/></label><label>Email<input value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></label><label>Opening hours<input value={settings.hours} onChange={e=>setSettings({...settings,hours:e.target.value})}/></label><button className="gold-button" type="submit"><Save size={16}/>Save settings</button></form>}
 {editing&&<div className="modal-backdrop"><form className="vehicle-editor" onSubmit={saveVehicle}><div className="panel-heading"><h2>{editing.id?"Edit vehicle":"Add vehicle"}</h2><button type="button" onClick={()=>setEditing(null)}>Close</button></div><div className="form-grid"><label>Name<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Make<input required value={editing.make} onChange={e=>setEditing({...editing,make:e.target.value})}/></label><label>Model<input required value={editing.model} onChange={e=>setEditing({...editing,model:e.target.value})}/></label><label>Year<input required type="number" value={editing.year} onChange={e=>setEditing({...editing,year:+e.target.value})}/></label><label>Mileage<input type="number" value={editing.mileage} onChange={e=>setEditing({...editing,mileage:+e.target.value})}/></label><label>Price (KES)<input type="number" value={editing.price} onChange={e=>setEditing({...editing,price:+e.target.value})}/></label><label>Fuel<select value={editing.fuel} onChange={e=>setEditing({...editing,fuel:e.target.value})}><option>Petrol</option><option>Diesel</option><option>Hybrid</option><option>Electric</option></select></label><label>Transmission<select value={editing.transmission} onChange={e=>setEditing({...editing,transmission:e.target.value})}><option>Automatic</option><option>Manual</option></select></label><label>Body<select value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}><option>SUV</option><option>Sedan</option><option>Pickup</option><option>Hatchback</option><option>Van</option></select></label><label>Source<select value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value as Vehicle["source"]})}><option>Imported</option><option>Local</option></select></label><label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Vehicle["status"]})}><option>Available</option><option>Reserved</option><option>Sold</option></select></label><label className="wide">Image URL<input value={editing.images[0]||""} onChange={e=>setEditing({...editing,images:e.target.value?[e.target.value]:[]})}/></label><label className="wide">Description<textarea rows={4} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label></div><button className="gold-button" type="submit"><Save size={16}/>Save vehicle</button></form></div>}</section></main>
}
function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="admin-stat"><div>{icon}</div><strong>{value}</strong><span>{label}</span></div>}
